apiVersion: v1
kind: PersistentVolume
metadata:
    name: fileserver
spec:
    capacity: 
        storage: 200G
    accessModes:
    - ReadWriteMany
    nfs: 
        path: /GKEvol1/pod1
        server: 10.90.99.90
