apiVersion: v1
kind: PersistentVolume
metadata:
    name: fileserver
spec:
    capacity: 
        storage: 200G
    accessModes:
    - ReadWriteMany
    nfs: 
        path: /vol1
        server: 10.44.163.114
