apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: fileserver-claim
    annotations: 
        volume.beta.kubernetes.io/storage-class: "nfs"
spec:
    accessModes:
    - ReadWriteMany
    volumeName: fileserver
    resources:
        requests:
            storage: 200G
