apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server3
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server3
  template:
    metadata:
      labels:
        role: nfs-server3
    spec:
      containers:
      - name: nfs-server3
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs3
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc3
      volumes:
        - name: mypvc3
          gcePersistentDisk:
            pdName: disk-1
            fsType: ext4
