apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server2
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server2
  template:
    metadata:
      labels:
        role: nfs-server2
    spec:
      containers:
      - name: nfs-server2
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs2
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc2
      volumes:
        - name: mypvc2
          gcePersistentDisk:
            pdName: gce-nfs-disk-3
            fsType: ext4
