apiVersion: v1
kind: Service
metadata:
  name: nfs-server3
spec:
  # clusterIP: 10.3.240.20
  ports:
    - name: nfs3
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server3
